### ISSUE TITLE
FIX [NEW CADT UI] - Need asterisks next to required fields in create project/unit modals

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/cadt-ui#1222]
Required fields should be shown with an asterisk in create modals.

![Image](https://github.com/Chia-Network/cadt-ui/assets/98057517/75b81f5d-d2e0-4726-bcc1-a1a3492bc76c)

**Comment by ccornick** [comment]
Working well on most fields, appears there is a field that was missed.



![Image](https://github.com/Chia-Network/cadt-ui/assets/98057517/7687e1a4-f8cd-42de-8780-c0e5bc4b9269)

**Comment by ccornick** [comment]
Additionally Validation Date needs an asterisk



![Image](https://github.com/Chia-Network/cadt-ui/assets/98057517/210f5693-7be7-4c00-9fed-2de7b2c617ce)

**Comment by wwills2** [comment]
the required validation and required markers should now match those of the old version
