### ISSUE TITLE
FIX [NEW CADT UI] - Unable to advance to different sections of the create project modal using the workflow nav at the top

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/cadt-ui#1228]
User should be able to advance to different sections of the workflow by clicking the numbers at the top. Currently only way to navigate is using back and next buttons.

![Image](https://github.com/Chia-Network/cadt-ui/assets/98057517/a2ffe342-09aa-4a20-97cd-8810b7735655)

**Comment by MichaelTaylor3D** [comment]
@ccornick this was done on purpose. It was leaving to many edge cases with data validation. I opted to make it a "wizard" where you have to go step by step.

**Comment by ccornick** [comment]
Closing as this functionality is determined to not be needed.
