### ISSUE TITLE
FIX [NEW CADT UI] - Once a project is committed, the counter for PENDING still stays at 1

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/cadt-ui#1230]
![Image](https://github.com/Chia-Network/cadt-ui/assets/98057517/0dafe6da-05f5-4529-9a69-5f0253390138)

Only one project has been staged/committed. Pending counter still shows as one, even though it finished committing.

**Comment by wwills2** [comment]
I was unable to replicate this. Are there anymore specifics on the test case which demonstrated the bug?

**Comment by ccornick** [comment]
Unable to reproduce. Closing.
