### ISSUE TITLE
FEAT: [NEW CADT UI] - Need to add edit org and delete org buttons to organizations page

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/cadt-ui#1242]
Need to be able to edit org (which should bring up a modal similar to create org) and delete org (which should bring up a confirmation modal).

**Comment by wwills2** [comment]
following up on this ticket after discussion in stand-up to see if the styling of these features needs to be changed or if it is acceptable the way it is.

**Comment by ccornick** [comment]
Closing as buttons already present
